stages:
    - deploy
    - package

deploy_main:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd server-main/server-main-api
        - mvn clean deploy -s ../../settings.xml

deploy_i18n:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd server-i18n/server-i18n-api
        - mvn clean deploy -s ../../settings.xml

package_gateway:
    stage: package
    only:
        - main
    tags:
        - dev
    artifacts:
        paths:
            - server-gateway/target/*.jar
    script:
        - cd server-gateway
        - mvn clean package
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/gateway:latest
        - docker push $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/gateway:latest
        - docker rmi $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/gateway:latest
package_main:
    stage: package
    only:
        - main
    tags:
        - dev
    artifacts:
        paths:
            - server-main/server-main-service/target/*.jar
    script:
        - cd server-main/server-main-service
        - mvn clean package
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/main:latest
        - docker push $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/main:latest
        - docker rmi $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/main:latest
package_i18n:
    stage: package
    only:
        - main
    tags:
        - dev
    artifacts:
        paths:
            - server-i18n/server-i18n-service/target/*.jar
    script:
        - cd server-i18n/server-i18n-service
        - mvn clean package
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/i18n:latest
        - docker push $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/i18n:latest
        - docker rmi $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/i18n:latest
