stages:
    - package
    - deploy

package-gateway:
    stage: package
    only:
        - /^gateway-.*$/
    tags:
        - dev
    script:
        - java -version
        - mvn -v
        - cd server-gateway
        - mvn clean package deploy -U -s ../settings.xml -Dmaven.test.skip=true
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/gateway:latest
        - docker push $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/gateway:latest
        - docker rmi $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/gateway:latest

package-main:
    stage: package
    only:
        - /^main-.*$/
    tags:
        - dev
    script:
        - java -version
        - mvn -v
        - cd server-main/server-main-api
        - mvn clean deploy -U -s ../../settings.xml -Dmaven.test.skip=true
        - cd ../../server-main/server-main-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/main:latest
        - docker push $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/main:latest
        - docker rmi $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/main:latest

package-i18n:
    stage: package
    only:
        - /^i18n-.*$/
    tags:
        - dev
    script:
        - java -version
        - mvn -v
        - cd server-i18n/server-i18n-api
        - mvn clean deploy -U -s ../../settings.xml -Dmaven.test.skip=true
        - cd ../../server-i18n/server-i18n-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/i18n:latest
        - docker push $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/i18n:latest
        - docker rmi $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/i18n:latest

package-wiki:
    stage: package
    only:
        - /^wiki-.*$/
    tags:
        - dev
    script:
        - java -version
        - mvn -v
        - cd server-wiki/server-wiki-service
        - mvn clean deploy -U -s ../../settings.xml -Dmaven.test.skip=true
        - cd ../../server-wiki/server-wiki-service
        - mvn clean package -U -s ../../settings.xml -Dmaven.test.skip=true
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/wiki:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/wiki:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/wiki:latest
        - docker push $CI_REGISTRY/clover/server/wiki:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/wiki:latest
        - docker rmi $CI_REGISTRY/clover/server/wiki:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/wiki:latest

deploy-gateway:
    stage: deploy
    only:
        - /^gateway-.*$/
    tags:
        - dev
    script:
        - cd ~/server/clover/server-gateway
        - docker compose down
        - docker compose up -d

deploy-main:
    stage: deploy
    only:
        - /^main-.*$/
    tags:
        - dev
    script:
        - cd ~/server/clover/server-main
        - docker compose down
        - docker compose up -d

deploy-i18n:
    stage: deploy
    only:
        - /^i18n-.*$/
    tags:
        - dev
    script:
        - cd ~/server/clover/server-i18n
        - docker compose down
        - docker compose up -d

deploy-wiki:
    stage: deploy
    only:
        - /^wiki-.*$/
    tags:
        - dev
    script:
        - cd ~/server/clover/server-wiki
        - docker compose down
        - docker compose up -d

deploy-i18n-maven-plugin:
    stage: deploy
    only:
        - /^maven-plugin-.*$/
    tags:
        - dev
    script:
        - cd i18n-maven-plugin
        - java -version
        - mvn -v
        - mvn clean deploy -U -s ../settings.xml