stages:
    - maven
    - package
    - deploy

maven-deploy:
    stage: maven
    only:
        - main
    tags:
        - dev
    script:
        - mvn clean deploy -U -s settings.xml

package-gateway:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - cd server-gateway
        - mvn clean package -U -s ../settings.xml
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/gateway:latest
        - docker push $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/gateway:latest
        - docker rmi $CI_REGISTRY/clover/server/gateway:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/gateway:latest

package-main:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - cd server-main/server-main-service
        - mvn clean package -U -s ../../settings.xml
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/main:latest
        - docker push $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/main:latest
        - docker rmi $CI_REGISTRY/clover/server/main:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/main:latest

package-i18n:
    stage: package
    only:
        - main
    tags:
        - dev
    script:
        - cd server-i18n/server-i18n-service
        - mvn clean package -U -s ../../settings.xml
        - docker login -u $DOCKER_USER --password $DOCKER_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID -f ./Dockerfile .
        - docker tag $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID $CI_REGISTRY/clover/server/i18n:latest
        - docker push $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID
        - docker push $CI_REGISTRY/clover/server/i18n:latest
        - docker rmi $CI_REGISTRY/clover/server/i18n:$CI_PIPELINE_ID
        - docker rmi $CI_REGISTRY/clover/server/i18n:latest

deploy-gateway:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd ~/server/clover/server-gateway
        - docker compose down
        - docker compose up -d

deploy-main:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd ~/server/clover/server-main
        - docker compose down
        - docker compose up -d

deploy-i18n:
    stage: deploy
    only:
        - main
    tags:
        - dev
    script:
        - cd ~/server/clover/server-i18n
        - docker compose down
        - docker compose up -d
